-- MySQL Workbench Synchronization
-- Generated: 2023-10-21 21:34
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: ferna

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `db_milan`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `db_milan`.`leituras` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
CHANGE COLUMN `pluviosidade` `Pluviosidade` INT(11) NOT NULL ,
CHANGE COLUMN `vento_vel` `Vento_vel` INT(11) NOT NULL ,
CHANGE COLUMN `vento_dir` `Vento_dir` VARCHAR(45) NOT NULL ,
CHANGE COLUMN `hora` `Hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ,
CHANGE COLUMN `umidade` `Umidade` INT(11) NOT NULL ,
CHANGE COLUMN `luminosidade` `Luminosidade` INT(11) NOT NULL ,
CHANGE COLUMN `indice_uv` `Indice_uv` INT(11) NOT NULL ,
CHANGE COLUMN `pressao` `Pressao` INT(11) NOT NULL ,
CHANGE COLUMN `altitude` `Altitude` INT(11) NOT NULL ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
