-- MySQL Workbench Synchronization
-- Generated: 2023-10-21 22:26
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: ferna

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA `db_milan`  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE `db_milan`.`leituras` 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ,
ADD COLUMN `Temperatura` INT(11) NOT NULL AFTER `id`,
CHANGE COLUMN `Indice_uv` `Indice_uv` INT(11) NOT NULL AFTER `Altitude`,
CHANGE COLUMN `Vento_vel` `Vento_vel` INT(11) NOT NULL AFTER `CO`,
CHANGE COLUMN `Vento_dir` `Vento_dir` VARCHAR(45) NOT NULL AFTER `Vento_vel`,
CHANGE COLUMN `Pluviosidade` `Pluviosidade` INT(11) NOT NULL AFTER `Vento_dir`,
CHANGE COLUMN `Luminosidade` `Luminosidade` INT(11) NOT NULL AFTER `Pluviosidade`,
CHANGE COLUMN `Hora` `Hora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `Luminosidade`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
